table_name = "performance_test"
connection_string = "https://admin:hugohugohugohugoxxxxxxxxxxxxxxxxxxxxxxxxxx@xdemo.eks1.us-east-1.aws.cratedb-dev.net:4200"

duration = 10
batch_size = 500
batch_interval = 50
threads = 8
objects = 0
dashboard = true
log_level = "info"
